### ISSUE TITLE
java.net.UnknownHostException: lab-core.egeria-catalog.svc.cluster.local

### ISSUE THREAD

**Issue by revit13** [IBM/the-mesh-for-data#110]
Executing instructions in https://github.com/IBM/the-mesh-for-data/tree/master/samples/kubeflow on ubuntu 18.04.5 with  kind version v0.9.0 go1.15.2 linux/amd64 I get the following error:  (taken from egr-connector logs, after executing "cat m4dapplication.yaml | sed "s/ASSET_ID/$ASSET_ID/g" | kubectl -n anonymous apply -f -" command under Data user instructions)

2020-11-02 06:42:50,945 INFO  com.ibm.egeria.EgeriaClient - New EgeriaClient created. AssetID={"ServerName":"cocoMDS3","AssetGuid":"e74be783-eebe-4896-921b-26a36d443263"}. serverName=cocoMDS3. assetGUID=e74be783-eebe-4896-921b-26a36d443263.
2020-11-02 06:42:50,946 INFO  com.ibm.egeria.EgeriaClient - Call Asset API
2020-11-02 06:42:50,946 INFO  com.ibm.egeria.EgeriaClient - Call Egeria API: GetAssetAPI, URL: https://lab-core.egeria-catalog.svc.cluster.local:9443/servers/cocoMDS3/open-metadata/common-services/asset-owner/connected-asset/users/calliequartile/assets/e74be783-eebe-4896-921b-26a36d443263
2020-11-02 06:42:56,761 ERROR com.ibm.egeria.EgeriaClient - Error calling GetAssetAPI API of EgeriaClient. Error java.net.UnknownHostException: lab-core.egeria-catalog.svc.cluster.local: Try again. Trace: java.net.UnknownHostException: lab-core.egeria-catalog.svc.cluster.local: Try again
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)   at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)       at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)      at java.net.InetAddress.getAllByName0(InetAddress.java:1276)    at j

**Comment by revit13** [comment]
The following fix solved the problem: (removing .cluster.local suffix from lab-core service in the following yaml files)

diff --git a/manager/config/integration-tests/deployment_configmap.yaml b/manager/config/integration-tests/deployment_configmap.yaml
index 4008796..a9e8829 100644
--- a/manager/config/integration-tests/deployment_configmap.yaml
+++ b/manager/config/integration-tests/deployment_configmap.yaml
@@ -37,8 +37,8 @@ data:

   #external services
   OPA_SERVER_URL: "opa:8181"
-  EGERIA_SERVER_URL: "https://lab-core.egeria-catalog.svc.cluster.local:9443"
+  EGERIA_SERVER_URL: "https://lab-core.egeria-catalog.svc:9443"
diff --git a/manager/config/prod/deployment_configmap.yaml b/manager/config/prod/deployment_configmap.yaml
index bafe80e..1f69d52 100644
--- a/manager/config/prod/deployment_configmap.yaml
+++ b/manager/config/prod/deployment_configmap.yaml
@@ -37,7 +37,7 @@ data:

   #external services
   OPA_SERVER_URL: "opa:8181"
-  EGERIA_SERVER_URL: "https://lab-core.egeria-catalog.svc.cluster.local:9443"
+  EGERIA_SERVER_URL: "https://lab-core.egeria-catalog.svc:9443"

   #external vault  variables
   USER_VAULT_ADDRESS: "http://vault.m4d-system.svc.cluster.local:8200/"

**Comment by roee88** [comment]
It's a workaround rather than a fix. Normally `.cluster.local` should be resolvable. I'm also not sure why the workaround works actually, my understanding is that <svc>.<namespace> is only resolved because the resolv.conf in pods makes it search .svc.cluster.local. Could you please follow https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/ to try to pinpoint the problem.

**Comment by roee88** [comment]
I read an Istio blog and one of its sections seemed relevant to this issue:
https://istio.io/latest/blog/2020/dns-proxy/#reduced-load-on-your-dns-servers-w-faster-resolution

It's possible that the /etc/resolv.conf on the machine you used made queries to fully qualified URLs fail. Although it's a machine setup issue, we should probably change it to use just service name when within the same namespace and <service name>.<namespace> otherwise. Would you like to take this and create a PR? 

You should fix your environment anyway, it may cause other problems :)

**Comment by revit13** [comment]
Sure, will create a pr for that.
